site:
  title: SUSE® Security Documentation
  url: /
  start_page: 5.4@security:en:overview.adoc

content:
  sources:
    - url: https://github.com/rancher/neuvector-product-docs.git
      branches: [main, 5.3]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: '@springio/antora-xref-extension'
  - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
    attributefile: ./product-docs-common/global-attributes.yml
    enabled: true

output:
  dir: build/site
